In [1]:
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'
columns = ['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age','Outcome']

df = pd.read_csv(url,names=columns)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [2]:
cols_with_missing_vals = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0,np.nan)

df.fillna(df.mean(),inplace=True)
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [3]:
x = df.drop('Outcome',axis = 1)
y = df['Outcome']

X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state = 42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [4]:
X_train.shape

(537, 8)

In [5]:
X_test.shape

(231, 8)

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

def objective(trial):
    n_estimators = trial.suggest_int('n_estimators',50,200)
    max_Depth = trial.suggest_int('max_depth',3,20)

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_Depth,
        random_state=42
    )

    score = cross_val_score(model,X_train,y_train,cv =3,scoring='accuracy').mean()
    return score

In [7]:
study = optuna.create_study(direction='maximize',sampler=optuna.samplers.TPESampler())
study.optimize(objective,n_trials=50)

[I 2026-07-13 19:04:02,831] A new study created in memory with name: no-name-e897ffdf-4b62-43ed-af65-a51e8baf6bdc
[I 2026-07-13 19:04:03,168] Trial 0 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 123, 'max_depth': 14}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-13 19:04:03,381] Trial 1 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 76, 'max_depth': 15}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-13 19:04:03,852] Trial 2 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 154, 'max_depth': 13}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-13 19:04:04,107] Trial 3 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 105, 'max_depth': 3}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-13 19:04:04,574] Trial 4 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 177, 'max_depth': 9}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-13 19:04:05,040] Trial 5 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 173, 'max_depth': 10}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-13 19:04:05,250] Trial 6 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 76, 'max_depth': 12}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-07-13 19:04:05,736] Trial 7 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 182, 'max_depth': 17}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-07-13 19:04:06,261] Trial 8 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 195, 'max_depth': 15}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:06,423] Trial 9 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 59, 'max_depth': 15}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:06,810] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 136, 'max_depth': 20}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:07,367] Trial 11 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 200, 'max_depth': 19}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:07,915] Trial 12 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 196, 'max_depth': 20}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:08,474] Trial 13 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 197, 'max_depth': 18}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:08,927] Trial 14 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 158, 'max_depth': 17}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:09,478] Trial 15 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 7}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:09,935] Trial 16 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 160, 'max_depth': 17}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:10,459] Trial 17 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 181, 'max_depth': 19}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:10,863] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 138, 'max_depth': 16}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:11,396] Trial 19 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 187, 'max_depth': 12}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:11,834] Trial 20 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 165, 'max_depth': 5}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:12,400] Trial 21 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 198, 'max_depth': 20}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:12,966] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 189, 'max_depth': 19}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:13,543] Trial 23 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:14,037] Trial 24 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 171, 'max_depth': 18}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:14,590] Trial 25 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 190, 'max_depth': 15}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:15,033] Trial 26 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 152, 'max_depth': 18}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:15,521] Trial 27 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 172, 'max_depth': 16}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:16,015] Trial 28 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 184, 'max_depth': 10}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:16,406] Trial 29 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 142, 'max_depth': 13}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:16,916] Trial 30 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 188, 'max_depth': 19}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:17,455] Trial 31 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 18}. Best is trial 8 with value: 0.7765363128491621.
[I 2026-07-13 19:04:17,979] Trial 32 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 193, 'max_depth': 16}. Best is trial 32 with value: 0.7783985102420856.
[I 2026-07-13 19:04:18,490] Trial 33 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 191, 'max_depth': 14}. Best is trial 32 with value: 0.7783985102420856.
[I 2026-07-13 19:04:18,972] Trial 34 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 177, 'max_depth': 16}. Best is trial 34 with value: 0.7783985102420857.
[I 2026-07-13 19:04:19,420] Trial 35 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 166, 'max_depth': 14}. Best is trial 34 with value: 0.7783985102420857.
[I 2026-07-13 19:04:19,739] Trial 36 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 117, 'max_depth': 16}. Best is trial 36 with value: 0.7802607076350093.
[I 2026-07-13 19:04:20,040] Trial 37 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 109, 'max_depth': 16}. Best is trial 36 with value: 0.7802607076350093.
[I 2026-07-13 19:04:20,342] Trial 38 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 110, 'max_depth': 16}. Best is trial 36 with value: 0.7802607076350093.
[I 2026-07-13 19:04:20,609] Trial 39 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 97, 'max_depth': 12}. Best is trial 36 with value: 0.7802607076350093.
[I 2026-07-13 19:04:20,935] Trial 40 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 119, 'max_depth': 13}. Best is trial 36 with value: 0.7802607076350093.
[I 2026-07-13 19:04:21,217] Trial 41 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 103, 'max_depth': 16}. Best is trial 36 with value: 0.7802607076350093.
[I 2026-07-13 19:04:21,541] Trial 42 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 120, 'max_depth': 16}. Best is trial 36 with value: 0.7802607076350093.
[I 2026-07-13 19:04:21,793] Trial 43 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 89, 'max_depth': 14}. Best is trial 36 with value: 0.7802607076350093.
[I 2026-07-13 19:04:22,098] Trial 44 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 110, 'max_depth': 15}. Best is trial 36 with value: 0.7802607076350093.
[I 2026-07-13 19:04:22,332] Trial 45 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 83, 'max_depth': 17}. Best is trial 36 with value: 0.7802607076350093.
[I 2026-07-13 19:04:22,502] Trial 46 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 59, 'max_depth': 14}. Best is trial 36 with value: 0.7802607076350093.
[I 2026-07-13 19:04:22,853] Trial 47 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 130, 'max_depth': 17}. Best is trial 36 with value: 0.7802607076350093.
[I 2026-07-13 19:04:23,164] Trial 48 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 114, 'max_depth': 15}. Best is trial 36 with value: 0.7802607076350093.
[I 2026-07-13 19:04:23,365] Trial 49 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 73, 'max_depth': 16}. Best is trial 36 with value: 0.7802607076350093.

In [8]:
study.best_trial.value

0.7802607076350093

In [9]:
study.best_trial.params

{'n_estimators': 117, 'max_depth': 16}

In [10]:
from sklearn.metrics import accuracy_score

best_model = RandomForestClassifier(**study.best_trial.params,random_state=42)

best_model.fit(X_train,y_train)

y_pred = best_model.predict(X_test)

test_accuracy = accuracy_score(y_test,y_pred)
print(f"Test accuracy with beest hyperparameters:{test_accuracy:.2f}")

Test accuracy with beest hyperparameters:0.73

### Samplers

random sampler

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

def objective1(trial):
    n_estimators = trial.suggest_int('n_estimators',50,200)
    max_Depth = trial.suggest_int('max_depth',3,20)

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_Depth,
        random_state=42
    )

    score = cross_val_score(model,X_train,y_train,cv =3,scoring='accuracy').mean()
    return score

In [12]:
study1 = optuna.create_study(direction='maximize',sampler=optuna.samplers.RandomSampler())
study1.optimize(objective1,n_trials=50)

[I 2026-07-13 19:04:23,554] A new study created in memory with name: no-name-37d8d0f2-b90d-4677-b31f-585dec31d1c3
[I 2026-07-13 19:04:23,897] Trial 0 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 123, 'max_depth': 11}. Best is trial 0 with value: 0.7635009310986964.
[I 2026-07-13 19:04:24,150] Trial 1 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 91, 'max_depth': 13}. Best is trial 0 with value: 0.7635009310986964.
[I 2026-07-13 19:04:24,608] Trial 2 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 168, 'max_depth': 16}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-07-13 19:04:24,998] Trial 3 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 143, 'max_depth': 13}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-07-13 19:04:25,198] Trial 4 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 71, 'max_depth': 20}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:25,611] Trial 5 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 150, 'max_depth': 13}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:25,855] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 89, 'max_depth': 15}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:26,119] Trial 7 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 91, 'max_depth': 18}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:26,537] Trial 8 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 151, 'max_depth': 18}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:26,956] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 155, 'max_depth': 12}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:27,312] Trial 10 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 130, 'max_depth': 11}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:27,738] Trial 11 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 171, 'max_depth': 5}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:28,015] Trial 12 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 107, 'max_depth': 7}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:28,238] Trial 13 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 78, 'max_depth': 12}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:28,477] Trial 14 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 85, 'max_depth': 19}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:28,837] Trial 15 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 143, 'max_depth': 5}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:29,139] Trial 16 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 109, 'max_depth': 13}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:29,500] Trial 17 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 139, 'max_depth': 6}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:30,002] Trial 18 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 194, 'max_depth': 6}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:30,277] Trial 19 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 108, 'max_depth': 5}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:30,522] Trial 20 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 87, 'max_depth': 16}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:30,980] Trial 21 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 170, 'max_depth': 9}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:31,464] Trial 22 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 176, 'max_depth': 12}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:31,682] Trial 23 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 84, 'max_depth': 5}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:32,020] Trial 24 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 131, 'max_depth': 6}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:32,389] Trial 25 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 145, 'max_depth': 5}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:32,812] Trial 26 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 155, 'max_depth': 10}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:33,190] Trial 27 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 139, 'max_depth': 11}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:33,394] Trial 28 finished with value: 0.756052141527002 and parameters: {'n_estimators': 73, 'max_depth': 10}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:33,865] Trial 29 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 190, 'max_depth': 5}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:34,336] Trial 30 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 183, 'max_depth': 7}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:34,759] Trial 31 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 173, 'max_depth': 5}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:35,089] Trial 32 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 122, 'max_depth': 14}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:35,375] Trial 33 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 107, 'max_depth': 9}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:35,814] Trial 34 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 183, 'max_depth': 4}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:36,283] Trial 35 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 172, 'max_depth': 14}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:36,465] Trial 36 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 72, 'max_depth': 5}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:36,849] Trial 37 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 19}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:37,003] Trial 38 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 59, 'max_depth': 5}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:37,455] Trial 39 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 168, 'max_depth': 18}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:37,944] Trial 40 finished with value: 0.756052141527002 and parameters: {'n_estimators': 192, 'max_depth': 6}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:38,167] Trial 41 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 81, 'max_depth': 14}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:38,546] Trial 42 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 141, 'max_depth': 20}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:38,781] Trial 43 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 83, 'max_depth': 19}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:39,126] Trial 44 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 134, 'max_depth': 7}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:39,503] Trial 45 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 142, 'max_depth': 11}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:40,024] Trial 46 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 193, 'max_depth': 19}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:40,192] Trial 47 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 60, 'max_depth': 18}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-07-13 19:04:40,394] Trial 48 finished with value: 0.7839851024208566 and parameters: {'n_estimators': 73, 'max_depth': 18}. Best is trial 48 with value: 0.7839851024208566.
[I 2026-07-13 19:04:40,837] Trial 49 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 165, 'max_depth': 19}. Best is trial 48 with value: 0.7839851024208566.

In [13]:
study1.best_trial.value

0.7839851024208566

In [14]:
study1.best_trial.params

{'n_estimators': 73, 'max_depth': 18}

In [15]:
best_model1 = RandomForestClassifier(**study1.best_trial.params,random_state=42)

best_model1.fit(X_train,y_train)

y_pred1 = best_model1.predict(X_test)

test_accuracy1 = accuracy_score(y_test,y_pred1)

print(f'Test accuracy on best hyperparameters:{test_accuracy1:.2f}')

Test accuracy on best hyperparameters:0.74

grid search

In [16]:
search_space = {
    'n_estimators' : [50,100,150,200],
    'max_depth' : [5,10,15,20]
}

In [17]:
study2 = optuna.create_study(direction='maximize',sampler=optuna.samplers.GridSampler(search_space))
study2.optimize(objective1)

[I 2026-07-13 19:04:40,974] A new study created in memory with name: no-name-173e2238-13c2-4a6f-9704-659438ffd6f3
[I 2026-07-13 19:04:41,227] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-07-13 19:04:41,632] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-07-13 19:04:41,775] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-13 19:04:42,050] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-13 19:04:42,327] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-13 19:04:42,485] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-13 19:04:42,887] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-13 19:04:43,319] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-13 19:04:43,755] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-13 19:04:44,324] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-13 19:04:44,906] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-13 19:04:45,460] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-13 19:04:46,015] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-13 19:04:46,152] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-07-13 19:04:46,454] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-07-13 19:04:46,618] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [18]:
study2.best_trial.value

0.7746741154562384

In [19]:
study2.best_trial.params

{'n_estimators': 50, 'max_depth': 5}

In [20]:
best_model2 = RandomForestClassifier(**study1.best_trial.params,random_state=42)

best_model2.fit(X_train,y_train)

y_pred2 = best_model2.predict(X_test)

test_accuracy2 = accuracy_score(y_test,y_pred2)

print(f'Test accuracy with best hyperparameters:{test_accuracy2:.2f}')

Test accuracy with best hyperparameters:0.74

### Optuna visualization

In [21]:
from optuna.visualization import plot_optimization_history,plot_parallel_coordinate,plot_slice,plot_contour,plot_param_importances

In [22]:
import plotly

##### optimization_history

In [23]:
plot_optimization_history(study).show()

##### Parallel coordinate plot

In [24]:
plot_parallel_coordinate(study).show()

##### Slice plot

In [25]:
plot_slice(study).show()

##### Contour plot

In [26]:
plot_contour(study).show()

##### Importance plot

In [27]:
plot_param_importances(study).show()

### Define by run feature

In [28]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC

In [34]:
def objective2(trial):

    classifier_name = trial.suggest_categorical('classifier',['SVM','RandomForest','GradientBoosting'])

    if classifier_name == 'SVM':
        c = trial.suggest_float('C',0.1,100,log =True)
        kernel = trial.suggest_categorical('kernel',['linear','rbf','poly','sigmoid'])
        gamma = trial.suggest_categorical('gamma',['scale','auto'])

        model = SVC(C=c,kernel=kernel,gamma=gamma,random_state=42)

    elif classifier_name == 'RandomForest':
        n_estimators = trial.suggest_int('n_estimators',50,300)
        max_depth = trial.suggest_int('max_depth',3,20)
        min_samples_split = trial.suggest_int('min_samples_split',2,10)
        min_samples_leaf = trial.suggest_int('min_sapmles_leaf',1,10)
        bootstrap = trial.suggest_categorical('bootstrap',[True,False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        n_estimators = trial.suggest_int('n_esttimators',50,300)
        learning_rate = trial.suggest_float('learning_rate',0.01,0.3,log =True)
        max_depth = trial.suggest_int('max_depth',3,20)
        min_samples_split = trial.suggest_int('min_samples_split',2,10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf',1,10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf
        )

    score = cross_val_score(model,X_train,y_train,cv=3,scoring='accuracy').mean()
    return score

In [35]:
study3 = optuna.create_study(direction='maximize')
study3.optimize(objective2,n_trials=100)

[I 2026-07-13 19:07:57,416] A new study created in memory with name: no-name-f89ec3a1-0164-4d0d-85d4-396df7e86462
[I 2026-07-13 19:07:57,430] Trial 0 finished with value: 0.6927374301675977 and parameters: {'classifier': 'SVM', 'C': 66.97645261714807, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 0 with value: 0.6927374301675977.
[I 2026-07-13 19:07:57,450] Trial 1 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.918701307709879, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-07-13 19:07:58,154] Trial 2 finished with value: 0.7541899441340782 and parameters: {'classifier': 'RandomForest', 'n_estimators': 284, 'max_depth': 7, 'min_samples_split': 9, 'min_sapmles_leaf': 9, 'bootstrap': True}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-07-13 19:07:59,271] Trial 3 finished with value: 0.7597765363128492 and parameters: {'classifier': 'GradientBoosting', 'n_esttimators': 219, 'learning_rate': 0.22322118365422525, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-07-13 19:07:59,683] Trial 4 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_esttimators': 67, 'learning_rate': 0.1926113609396429, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 8}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-07-13 19:08:00,159] Trial 5 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 206, 'max_depth': 3, 'min_samples_split': 9, 'min_sapmles_leaf': 9, 'bootstrap': True}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-07-13 19:08:00,179] Trial 6 finished with value: 0.7113594040968342 and parameters: {'classifier': 'SVM', 'C': 13.067168367634071, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-07-13 19:08:00,893] Trial 7 finished with value: 0.7206703910614526 and parameters: {'classifier': 'GradientBoosting', 'n_esttimators': 128, 'learning_rate': 0.16342056004914843, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 9}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-07-13 19:08:01,328] Trial 8 finished with value: 0.7579143389199254 and parameters: {'classifier': 'RandomForest', 'n_estimators': 177, 'max_depth': 15, 'min_samples_split': 2, 'min_sapmles_leaf': 6, 'bootstrap': True}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-07-13 19:08:01,713] Trial 9 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_esttimators': 98, 'learning_rate': 0.28378795970327786, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-07-13 19:08:01,735] Trial 10 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1451857289896656, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:01,750] Trial 11 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10600952420896315, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:01,760] Trial 12 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11221847633486634, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:01,774] Trial 13 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1006926171966721, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:01,793] Trial 14 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.5279400428811775, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:01,807] Trial 15 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4663998398015437, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:01,821] Trial 16 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4058242941482499, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:01,833] Trial 17 finished with value: 0.7262569832402234 and parameters: {'classifier': 'SVM', 'C': 0.2952955575855586, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:01,853] Trial 18 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 1.3661847493647006, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:02,020] Trial 19 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 5, 'min_sapmles_leaf': 1, 'bootstrap': False}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:02,041] Trial 20 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.13773031112398948, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:02,055] Trial 21 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1004497203062923, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:02,069] Trial 22 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2252653872431422, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:02,085] Trial 23 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8758046125217618, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:02,100] Trial 24 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19119561187031317, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:02,114] Trial 25 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1844270592133905, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:02,125] Trial 26 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10878486372290255, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:02,141] Trial 27 finished with value: 0.7337057728119181 and parameters: {'classifier': 'SVM', 'C': 1.4112134816512991, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:02,317] Trial 28 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 65, 'max_depth': 13, 'min_samples_split': 5, 'min_sapmles_leaf': 1, 'bootstrap': False}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:04,063] Trial 29 finished with value: 0.7616387337057727 and parameters: {'classifier': 'GradientBoosting', 'n_esttimators': 280, 'learning_rate': 0.01082810932690316, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 6}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:04,075] Trial 30 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 0.3409291956818437, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:04,101] Trial 31 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11440903579307454, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:04,116] Trial 32 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.18941069435077598, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:04,131] Trial 33 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21113738855063885, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:04,143] Trial 34 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10571750097710665, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:04,163] Trial 35 finished with value: 0.7690875232774674 and parameters: {'classifier': 'SVM', 'C': 0.6327510314108024, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:04,176] Trial 36 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2854407506248286, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:05,488] Trial 37 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_esttimators': 193, 'learning_rate': 0.03300149560078847, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:06,141] Trial 38 finished with value: 0.7746741154562383 and parameters: {'classifier': 'RandomForest', 'n_estimators': 297, 'max_depth': 9, 'min_samples_split': 7, 'min_sapmles_leaf': 5, 'bootstrap': False}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:06,155] Trial 39 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15496279103639712, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:08,588] Trial 40 finished with value: 0.7430167597765363 and parameters: {'classifier': 'GradientBoosting', 'n_esttimators': 286, 'learning_rate': 0.052546949176474456, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:08,613] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15796514371182033, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:08,631] Trial 42 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15675378051244376, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:08,651] Trial 43 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.28096897536329407, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:08,671] Trial 44 finished with value: 0.7001862197392924 and parameters: {'classifier': 'SVM', 'C': 24.76797846355689, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:08,690] Trial 45 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14314958804263161, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:09,071] Trial 46 finished with value: 0.7448789571694601 and parameters: {'classifier': 'RandomForest', 'n_estimators': 160, 'max_depth': 3, 'min_samples_split': 10, 'min_sapmles_leaf': 5, 'bootstrap': False}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:09,088] Trial 47 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1642455126788294, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:09,105] Trial 48 finished with value: 0.7243947858472998 and parameters: {'classifier': 'SVM', 'C': 0.2754937583373287, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:09,895] Trial 49 finished with value: 0.7728119180633147 and parameters: {'classifier': 'GradientBoosting', 'n_esttimators': 168, 'learning_rate': 0.010672292487254726, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 10}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:09,911] Trial 50 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7459502664080895, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:09,926] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13034398965620855, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:09,941] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1343117506801849, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,118] Trial 53 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 97.43122075995386, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,131] Trial 54 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1390323882497133, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,154] Trial 55 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.4254052168147324, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,166] Trial 56 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23685463968974296, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,515] Trial 57 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 126, 'max_depth': 16, 'min_samples_split': 2, 'min_sapmles_leaf': 3, 'bootstrap': True}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,539] Trial 58 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.514711602960455, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,555] Trial 59 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10804663015232137, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,569] Trial 60 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 0.3760261653929934, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,583] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13731392495554873, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,597] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13357242491751206, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,613] Trial 63 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1003924575482399, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,630] Trial 64 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.22227119432389494, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,649] Trial 65 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1437598816300124, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,668] Trial 66 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19575719962488922, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:10,688] Trial 67 finished with value: 0.750465549348231 and parameters: {'classifier': 'SVM', 'C': 0.13026035709793568, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:13,063] Trial 68 finished with value: 0.664804469273743 and parameters: {'classifier': 'GradientBoosting', 'n_esttimators': 235, 'learning_rate': 0.0654361198200986, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:13,080] Trial 69 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.25914145730595317, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:13,628] Trial 70 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 243, 'max_depth': 10, 'min_samples_split': 8, 'min_sapmles_leaf': 10, 'bootstrap': False}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:13,642] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1411331203580575, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:13,658] Trial 72 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19005246368392884, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:13,673] Trial 73 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12591004082706467, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:13,688] Trial 74 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17259121330358068, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:13,701] Trial 75 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10005574471614533, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:13,716] Trial 76 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.32849616733484105, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:13,731] Trial 77 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.22368153573552424, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:13,745] Trial 78 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12665421408077807, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:13,764] Trial 79 finished with value: 0.7579143389199254 and parameters: {'classifier': 'SVM', 'C': 0.5068749342428085, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:14,107] Trial 80 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_esttimators': 50, 'learning_rate': 0.021721218096712007, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-07-13 19:08:14,120] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15564149899592292, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.

In [36]:
study3.best_trial.value

0.7895716945996275

In [37]:
study3.best_trial.params

{'classifier': 'SVM',
 'C': 0.1451857289896656,
 'kernel': 'linear',
 'gamma': 'scale'}

In [39]:
study3.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_min_sapmles_leaf,params_n_estimators,params_n_esttimators,state
0,0,0.692737,2026-07-13 19:07:57.416424,2026-07-13 19:07:57.430609,0 days 00:00:00.014185,66.976453,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.785847,2026-07-13 19:07:57.430609,2026-07-13 19:07:57.450842,0 days 00:00:00.020233,2.918701,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,0.754190,2026-07-13 19:07:57.451847,2026-07-13 19:07:58.154017,0 days 00:00:00.702170,NaN,True,RandomForest,NaN,NaN,NaN,7.0,NaN,9.0,9.0,284.0,NaN,COMPLETE
3,3,0.759777,2026-07-13 19:07:58.154017,2026-07-13 19:07:59.271462,0 days 00:00:01.117445,NaN,NaN,GradientBoosting,NaN,NaN,0.223221,7.0,2.0,7.0,NaN,NaN,219.0,COMPLETE
4,4,0.737430,2026-07-13 19:07:59.271462,2026-07-13 19:07:59.683324,0 days 00:00:00.411862,NaN,NaN,GradientBoosting,NaN,NaN,0.192611,20.0,8.0,9.0,NaN,NaN,67.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.785847,2026-07-13 19:08:14.661394,2026-07-13 19:08:14.677275,0 days 00:00:00.015881,0.249399,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.785847,2026-07-13 19:08:14.678283,2026-07-13 19:08:14.761584,0 days 00:00:00.083301,35.075957,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.785847,2026-07-13 19:08:14.762582,2026-07-13 19:08:14.776607,0 days 00:00:00.014025,0.192865,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.731844,2026-07-13 19:08:14.777598,2026-07-13 19:08:15.694994,0 days 00:00:00.917396,NaN,NaN,GradientBoosting,NaN,NaN,0.098546,20.0,8.0,6.0,NaN,NaN,148.0,COMPLETE
99,99,0.774674,2026-07-13 19:08:15.695997,2026-07-13 19:08:15.713074,0 days 00:00:00.017077,0.118534,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE

to see which algo ran for how many times

In [40]:
study3.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 79
GradientBoosting    11
RandomForest        10
Name: count, dtype: int64

to see avg accuracy of each algo

In [41]:
study3.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.740139
RandomForest        0.761825
SVM                 0.776866
Name: value, dtype: float64

In [42]:
plot_optimization_history(study3).show()